Repository secondlife/autobuild, pull requests merged in 2022-09, with the labels that each got.

#1 Publish new versions to PyPI
  .github/workflows/ci.yaml
  setup.py
  setup_cxfreeze.py
Labels: ignore-for-release

#2 Add JSON format option for package results file
  autobuild/autobuild_tool_package.py
  tests/test_package.py
Labels: enhancement

#4 Add blake2b hashing support
  autobuild/autobuild_tool_edit.py
  autobuild/autobuild_tool_package.py
  autobuild/common.py
  autobuild/hash_algorithms.py
  tests/test_package.py
Labels: enhancement

#6 Add zstandard support for tarfile compression along with xz, and gzip
  autobuild/autobuild_tool_install.py
  autobuild/autobuild_tool_package.py
  autobuild/common.py
  setup.py
  tests/data/bogus-0.1-common-111.tar.gz
  tests/data/bogus-0.1-common-111.tar.xz
  tests/data/bogus-0.1-common-111.tar.zst
  tests/data/bogus-0.1-common-111.zip
  tests/test_graph.py
  tests/test_install.py
  tests/test_package.py
Labels: enhancement

#7 Export cpu core count as AUTOBUILD_CPU_COUNT for build scripts
  autobuild/common.py
Labels: enhancement

#8 Add support for downloading packages from private sources
  README.md
  autobuild/autobuild_tool_install.py
  autobuild/autobuild_tool_installables.py
  autobuild/common.py
  tests/test_install.py
Labels: enhancement

#9 Do not pass Authorization header to redirects
  autobuild/autobuild_tool_install.py
  tests/test_install.py
Labels: bug

#10 Fix windows tests
  .github/workflows/ci.yaml
  .gitignore
  autobuild/autobuild_tool_configure.py
  autobuild/common.py
  tests/basetest.py
  tests/bin/autobuild
  tests/bin/autobuild.cmd
  tests/executables/__init__.py
  tests/executables/echo.py
  tests/executables/envtest.py
  tests/executables/noop.py
  tests/test_build_id.py
  tests/test_executable.py
  tests/test_graph.py
  tests/test_source_environment.py
Labels: ignore-for-release

#11 Add SHA1, SHA256 package hashes
  autobuild/autobuild_tool_edit.py
  autobuild/autobuild_tool_package.py
  autobuild/common.py
  autobuild/hash_algorithms.py
  tests/test_package.py
Labels: enhancement
